## Folder Structure
DATASET_FOLDER = 'data/BallroomData'
AUDIO_FOLDER_PATH = f'{DATASET_FOLDER}/audio_files'
SPECTROGRAM_FOLDER_PATH = f'{DATASET_FOLDER}/spectrograms'
SPLIT_SPECTROGRAM_FOLDER_PATH = f'{DATASET_FOLDER}/split_spectrograms'
ALL_BALLROOM_FILES = f'{DATASET_FOLDER}/allBallroomFiles'
ALL_BALLROOM_SPECTROGRAMS = f'{DATASET_FOLDER}/allBallroomSpectrograms'


